Автор материала: Юрий Кашницкий (@yorko в Slack ODS). Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

## <center>Анализ данных по доходу населения UCI Adult</center>

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным репозитория UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) (качать данные не надо – они уже есть в репозитории).**
Уникальные значения признаков (больше информации по ссылке выше):
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("../data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?**

In [3]:
# Ваш код здесь
data['sex'].value_countss()

Male      21790
Female    10771
Name: sex, dtype: int64

##

**2. Каков средний возраст (признак *age*) женщин?**

In [6]:
# Ваш код здесь
data[data['sex']=='Female']['age'].mean()

36.85823043357163

**3. Какова доля граждан Германии (признак *native-country*)?**

In [7]:
# Ваш код здесь
len(data[data['native-country']=='Germany'])/len(data)

0.004207487485028101

**4-5. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год? **

In [10]:
# Ваш код здесь
data[['age','salary']].groupby('salary')['age'].mean()

salary
<=50K    36.783738
>50K     44.249841
Name: age, dtype: float64

In [19]:
data[['age','salary']].groupby('salary')['age'].std()

salary
<=50K    14.020088
>50K     10.519028
Name: age, dtype: float64

**6. Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [11]:
# Ваш код здесь
y = data[data['salary']=='>50K']
education_filter = \
(y['education'] == 'Bachelors') | \
(y['education'] == 'Prof-school') | \
(y['education'] == 'Assoc-acdm') |  \
(y['education'] == 'Assoc-voc') | \
(y['education'] == 'Masters') | \
(y['education'] == 'Doctorate') | \
(y['education'] == 'HS-grad') | \
(y['education'] == 'Some-college') 

education_filter.all()

False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [12]:
# Ваш код здесь
data[['age','race']].groupby('race').describe()

                        age                                                \
                      count       mean        std   min   25%   50%   75%
race
Amer-Indian-Eskimo    311.0  37.173633  12.447130  17.0  28.0  35.0  45.5
Asian-Pac-Islander   1039.0  37.746872  12.825133  17.0  28.0  36.0  45.0
Black                3124.0  37.767926  12.759290  17.0  28.0  36.0  46.0
Other                 271.0  33.457565  11.538865  17.0  25.0  31.0  41.0
White               27816.0  38.769881  13.782306  17.0  28.0  37.0  48.0


                     max
race
Amer-Indian-Eskimo  82.0
Asian-Pac-Islander  90.0
Black               90.0
Other               77.0
White               90.0

In [13]:
data[data['race']=='Amer-Indian-Eskimo']['age'].max()

82

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [14]:
# Ваш код здесь
y = data[data['salary']=='>50K']
married_filter = \
(y['marital-status'] == 'Married-civ-spouse') | \
(y['marital-status'] == 'Married-spouse-absent') | \
(y['marital-status'] == 'Married-AF-spouse')
z = len(y[married_filter])/len(y)
z1=(len(y)-len(y[married_filter]))/len(y)
if z>z1: 
    print('Среди много зарабатывающих больше женатых')
if z1>z:
    print ('Среди мног зарабатывающих больше холостых')

Среди много зарабатывающих больше женатых

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [15]:
# Ваш код здесь
data['hours-per-week'].max()

99

In [16]:
x=data[data['hours-per-week']==data['hours-per-week'].max()]
print (len(x))

85

In [17]:
len(x[x['salary']=='>50K'])/len(x)

0.29411764705882354

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [18]:
# Ваш код здесь
x1=data.groupby(['native-country','salary'])
x1['hours-per-week'].mean()

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64